/* GENERATED - do not edit this file.
 *
 * Built by `python plugin/vegas/bundle.py` from, in order:
 *   plugin/common/aicut_model.js
 *   plugin/common/aicut_engine.js
 *   plugin/vegas/aicut_vegas_time.js
 *   plugin/vegas/aicut_vegas_body.js
 *
 * Edit those and build again. VEGAS compiles one script file at a time, which
 * is the only reason this file exists; the parts above are what the tests run.
 */

import System;
import System.IO;
import System.Net;
import System.Text;
import System.Windows.Forms;
import ScriptPortal.Vegas;

/* ==== aicut_model.js ==== */
/* Reading the Common Edit Model inside an editor (플러그인 기획안 37장, 38장).
 *
 * 37장 puts this structure between the AI Engine and any editor API:
 *
 *     AI Engine -> Common Edit Model -> Editor Adapter -> 편집기
 *
 * This is the JavaScript twin of `aicut_model.py`, for the editors that script
 * in JavaScript rather than Python. It answers the same questions in the same
 * words, so an adapter written against either reads one meaning of the model
 * and not two - which is the whole point of 37장 putting a layer here at all.
 *
 * Nothing in this file touches an editor, so it runs under plain node, which
 * is how it is tested on a machine with no Adobe install on it.
 *
 * ES3 on purpose: ExtendScript is not modern JavaScript. No let, no const, no
 * arrow functions, no JSON guarantee.
 */

var aicutModel = (function () {
    "use strict";

    function ModelError(message) {
        this.name = "ModelError";
        this.message = message;
    }
    ModelError.prototype = new Error();

    function fail(message) {
        throw new ModelError(message);
    }

    function parse(text, where) {
        var model;
        try {
            // ExtendScript has no JSON in older hosts, so eval is the fallback
            // every Adobe script uses. The input is a document aicut wrote.
            model = (typeof JSON !== "undefined" && JSON.parse)
                ? JSON.parse(text)
                : eval("(" + text + ")");
        } catch (e) {
            fail((where || "the model") + " is not valid JSON: " + e.message);
        }
        return validated(model, where);
    }

    /* Refuse a document that is not a Common Edit Model, saying which it is. */
    function validated(model, where) {
        var name = where || "this file";
        if (!model || typeof model !== "object") {
            fail("an edit model is a JSON object");
        }
        if (model.cuts && !model.sequences) {
            fail("this is an aicut edit plan, not a Common Edit Model. 37장 has "
                 + "the adapter read the model, so ask the running engine for it: "
                 + "start it with 'aicut ui' and fetch "
                 + "http://127.0.0.1:8765/api/episodes/<id>/edit-model.");
        }
        if (!model.sequences) {
            fail(name + " has no 'sequences'; it is not a Common Edit Model");
        }
        if (!model.sequences.length) {
            fail("this model has no sequence in it - there is no timeline to build");
        }
        return model;
    }

    /* Where the file for one media id is, as the model states it. */
    function mediaPath(model, mediaId) {
        var media = model.media || [];
        var i, path;
        for (i = 0; i < media.length; i++) {
            if (media[i].media_id === mediaId) {
                path = media[i].path || "";
                if (!path) { fail("media " + mediaId + " has no path"); }
                return path;
            }
        }
        fail("the model has no media called " + mediaId);
    }

    function sequences(model) {
        return (model.sequences || []).slice(0);
    }

    /* The sequence's tracks of one kind, in index order.
     *
     * 24장: 필요한 Track을 AI가 구성한다. There are as many as the model has and
     * no more, so an adapter creating a fixed set would add empty ones. */
    function tracks(sequence, kind) {
        var all = sequence.tracks || [];
        var out = [];
        var i;
        for (i = 0; i < all.length; i++) {
            if (all[i].kind === kind) { out.push(all[i]); }
        }
        out.sort(function (x, y) { return (x.index || 0) - (y.index || 0); });
        return out;
    }

    /* The parts of one clip that survive pacing, in source seconds.
     *
     * A clip carries the spans an editor must drop from inside it (9.3); a
     * timeline that ignores them plays the dead air the plan decided to remove.
     */
    function keptSpans(clip) {
        var spans = [[Number(clip.in_point_sec), Number(clip.out_point_sec)]];
        var removals = [];
        var raw = clip.remove_spans || [];
        var i, j, out, start, end, a, b;

        for (i = 0; i < raw.length; i++) {
            removals.push([Number(raw[i][0]), Number(raw[i][1])]);
        }
        removals.sort(function (x, y) { return x[0] - y[0]; });

        for (i = 0; i < removals.length; i++) {
            start = removals[i][0];
            end = removals[i][1];
            out = [];
            for (j = 0; j < spans.length; j++) {
                a = spans[j][0];
                b = spans[j][1];
                if (end <= a || start >= b) {
                    out.push([a, b]);
                    continue;
                }
                if (start > a) { out.push([a, Math.min(start, b)]); }
                if (end < b) { out.push([Math.max(end, a), b]); }
            }
            spans = out;
        }

        out = [];
        for (i = 0; i < spans.length; i++) {
            if (spans[i][1] - spans[i][0] > 1e-3) { out.push(spans[i]); }
        }
        return out;
    }

    /* Every clip of the main video track, in timeline order.
     *
     * Timeline order, not source order: 2.4 lets a video open on a moment that
     * happened last, and sorting by in-point would quietly rebuild the
     * broadcast. */
    function videoClips(sequence) {
        var video = tracks(sequence, "video");
        var clips;
        if (!video.length) { fail("this sequence has no video track"); }
        clips = (video[0].clips || []).slice(0);
        clips.sort(function (x, y) {
            return (x.timeline_position_sec || 0) - (y.timeline_position_sec || 0);
        });
        return clips;
    }

    /* Every surviving span as frames, in timeline order.
     *
     * The frame rate is the editor's, not the model's: a sequence built at a
     * different rate slides every cut, and the sequence the adapter is filling
     * is the one that decides.
     *
     * `endFrameInclusive` is the editor's own convention and has to be stated
     * by the adapter: Resolve's endFrame is the last frame of the clip,
     * Premiere's out point is the first frame after it. One frame either way on
     * every cut is not visible until the export. */
    function frameRanges(sequence, fps, endFrameInclusive) {
        var ranges = [];
        var clips, spans, i, j, startFrame, endFrame;
        if (!(fps > 0)) { fail("frame rate must be positive, got " + fps); }
        clips = videoClips(sequence);
        for (i = 0; i < clips.length; i++) {
            spans = keptSpans(clips[i]);
            for (j = 0; j < spans.length; j++) {
                startFrame = Math.round(spans[j][0] * fps);
                endFrame = Math.round(spans[j][1] * fps);
                if (endFrameInclusive) { endFrame -= 1; }
                if (endFrameInclusive ? (endFrame < startFrame) : (endFrame <= startFrame)) {
                    // Shorter than one frame at this rate. Reported by
                    // droppedSpans rather than silently shifting what follows.
                    continue;
                }
                ranges.push({
                    startFrame: startFrame,
                    endFrame: endFrame,
                    frames: endFrameInclusive
                        ? (endFrame - startFrame + 1)
                        : (endFrame - startFrame),
                    clip: clips[i]
                });
            }
        }
        if (!ranges.length) {
            fail("every clip in this sequence is shorter than one frame at " + fps + " fps");
        }
        return ranges;
    }

    /* Spans too short to survive at this frame rate, so the caller can say so. */
    function droppedSpans(sequence, fps) {
        var dropped = [];
        var clips = videoClips(sequence);
        var i, j, spans;
        for (i = 0; i < clips.length; i++) {
            spans = keptSpans(clips[i]);
            for (j = 0; j < spans.length; j++) {
                if (Math.round(spans[j][1] * fps) <= Math.round(spans[j][0] * fps)) {
                    dropped.push(spans[j]);
                }
            }
        }
        return dropped;
    }

    /* A name a person can find again, not a bare id.
     *
     * 25장's default is a new sequence beside what the operator built, so the
     * name is what tells the two apart in their bin. */
    function timelineName(model, sequence) {
        var stated = String(sequence.name || "");
        stated = stated.replace(/^\s+|\s+$/g, "");
        if (stated) { return stated; }
        return "AI_" + String(sequence.sequence_id || "sequence").substring(0, 8);
    }

    /* Every caption, in time order, from whatever subtitle tracks exist. */
    function subtitles(sequence) {
        var found = tracks(sequence, "subtitle");
        var lines = [];
        var i, j, rows;
        for (i = 0; i < found.length; i++) {
            rows = found[i].subtitles || [];
            for (j = 0; j < rows.length; j++) { lines.push(rows[j]); }
        }
        lines.sort(function (x, y) {
            return (x.start_sec || 0) - (y.start_sec || 0);
        });
        return lines;
    }

    /* Sound the model places itself - BGM and effects - with its track name.
     *
     * The video clips' own audio is not here: 24장 gives 원본 음성 its own track
     * and both Resolve and Premiere place a linked A/V clip, so an adapter that
     * also laid these down would double the source audio. */
    function audioClips(sequence) {
        var found = tracks(sequence, "audio");
        var placed = [];
        var i, j, rows;
        for (i = 0; i < found.length; i++) {
            rows = found[i].audio || [];
            for (j = 0; j < rows.length; j++) {
                placed.push({track: found[i].name || "", clip: rows[j]});
            }
        }
        return placed;
    }

    function baseName(path) {
        var text = String(path).replace(/\\/g, "/");
        var parts = text.split("/");
        return parts[parts.length - 1] || text;
    }

    /* One paragraph a person can check the timeline against. */
    function summary(model, sequence, fps, endFrameInclusive) {
        var ranges = frameRanges(sequence, fps, endFrameInclusive);
        var frames = 0;
        var source = (model.media && model.media.length)
            ? baseName(mediaPath(model, "source")) : "?";
        var i;
        for (i = 0; i < ranges.length; i++) { frames += ranges[i].frames; }
        return ranges.length + " clips, " + (frames / fps).toFixed(1) + "s at "
            + fps + " fps, from " + source;
    }

    return {
        ModelError: ModelError,
        parse: parse,
        validated: validated,
        mediaPath: mediaPath,
        sequences: sequences,
        tracks: tracks,
        keptSpans: keptSpans,
        videoClips: videoClips,
        frameRanges: frameRanges,
        droppedSpans: droppedSpans,
        timelineName: timelineName,
        subtitles: subtitles,
        audioClips: audioClips,
        baseName: baseName,
        summary: summary
    };
}());

// node, for the tests. ExtendScript has no module and must not see this.

/* ==== aicut_engine.js ==== */
/* Talking to the AI Engine from an editor that scripts in JavaScript
 * (36장 9번 AI Engine Connector).
 *
 * The plugin does not analyse anything. 35장: AI Engine은 영상의 "두뇌"이고
 * Plugin은 편집기와 AI를 연결하는 "손"이다. This is the wire between them, and
 * it is the JavaScript twin of `aicut_engine.py` - the same five calls:
 *
 *     check()                     the engine is up, and which profiles it holds
 *     submit(source)              hand it the broadcast the editor has open
 *     job(jobId)                  what it is doing now (26장's progress screen)
 *     episodes(projectId)         what it decided to make
 *     editModel(episodeId, mode)  the Common Edit Model for one of them (37장)
 *
 * ExtendScript has no XMLHttpRequest and no fetch. It has a raw `Socket`, so
 * the HTTP is written out here by hand. The socket itself is passed in as a
 * `transport` - a function that takes the request text and returns the reply -
 * for two reasons: the request building and the reply parsing are then testable
 * under node, which has no ExtendScript Socket, and an editor whose scripting
 * host does have a real HTTP client can hand one over instead.
 */

var aicutEngine = (function () {
    "use strict";

    var DEFAULT_HOST = "127.0.0.1";
    //: The state a run reaches when it finished but the pipeline failed inside it.
    var FAILED_STATE = "FAILED";
    var DEFAULT_PORT = 8765;

    function EngineError(message) {
        this.name = "EngineError";
        this.message = message;
    }
    EngineError.prototype = new Error();

    function fail(message) {
        throw new EngineError(message);
    }

    function jsonEncode(value) {
        if (typeof JSON !== "undefined" && JSON.stringify) {
            return JSON.stringify(value);
        }
        return encodeValue(value);
    }

    /* A JSON writer for the hosts that have no JSON object. Only what the
     * engine is ever sent: strings, numbers, booleans, null, arrays, objects. */
    function encodeValue(value) {
        var parts = [];
        var key, i;
        if (value === null || value === undefined) { return "null"; }
        if (typeof value === "string") { return encodeString(value); }
        if (typeof value === "number") { return isFinite(value) ? String(value) : "null"; }
        if (typeof value === "boolean") { return value ? "true" : "false"; }
        if (value instanceof Array) {
            for (i = 0; i < value.length; i++) { parts.push(encodeValue(value[i])); }
            return "[" + parts.join(",") + "]";
        }
        for (key in value) {
            if (value.hasOwnProperty(key)) {
                parts.push(encodeString(key) + ":" + encodeValue(value[key]));
            }
        }
        return "{" + parts.join(",") + "}";
    }

    function encodeString(text) {
        var out = "";
        var i, ch, code;
        for (i = 0; i < text.length; i++) {
            ch = text.charAt(i);
            code = text.charCodeAt(i);
            if (ch === "\"" || ch === "\\") { out += "\\" + ch; }
            else if (ch === "\n") { out += "\\n"; }
            else if (ch === "\r") { out += "\\r"; }
            else if (ch === "\t") { out += "\\t"; }
            else if (code < 32 || code > 126) {
                // Non-ASCII goes out escaped: a path with Korean in it is
                // ordinary here, and the socket writes bytes, not characters.
                out += "\\u" + ("000" + code.toString(16)).slice(-4);
            } else { out += ch; }
        }
        return "\"" + out + "\"";
    }

    function jsonDecode(text, where) {
        try {
            return (typeof JSON !== "undefined" && JSON.parse)
                ? JSON.parse(text)
                : eval("(" + text + ")");
        } catch (e) {
            fail(where + " did not return JSON");
        }
    }

    /* The bytes of one HTTP/1.0 request. 1.0 rather than 1.1 on purpose: it
     * closes the connection at the end of the reply, which is how a raw socket
     * knows the body has finished without parsing chunked encoding. */
    function buildRequest(method, path, body, options) {
        var host = options.host + ":" + options.port;
        var lines = [method + " " + path + " HTTP/1.0",
                     "Host: " + host,
                     "Accept: application/json",
                     "Connection: close"];
        var payload = "";
        if (body !== null && body !== undefined) {
            payload = jsonEncode(body);
            lines.push("Content-Type: application/json");
            lines.push("Content-Length: " + byteLength(payload));
        }
        if (options.apiKey) {
            lines.push("Authorization: Bearer " + options.apiKey);
        }
        return lines.join("\r\n") + "\r\n\r\n" + payload;
    }

    /* Content-Length counts bytes, and the payload is escaped to ASCII by
     * `encodeString`, so its length in characters is its length in bytes.
     * JSON.stringify does not escape non-ASCII, so those are counted here. */
    function byteLength(text) {
        var bytes = 0;
        var i, code;
        for (i = 0; i < text.length; i++) {
            code = text.charCodeAt(i);
            if (code < 0x80) { bytes += 1; }
            else if (code < 0x800) { bytes += 2; }
            else { bytes += 3; }
        }
        return bytes;
    }

    /* Status line, headers and body out of one HTTP reply. */
    function parseResponse(raw, method, path) {
        var split, head, body, status;
        if (!raw) {
            fail("no reply from the engine for " + method + " " + path
                 + ". Start it with 'aicut ui'.");
        }
        split = raw.indexOf("\r\n\r\n");
        if (split < 0) { split = raw.indexOf("\n\n"); }
        head = split < 0 ? raw : raw.substring(0, split);
        body = split < 0 ? "" : raw.substring(split + (raw.charAt(split) === "\r" ? 4 : 2));
        status = Number(String(head.split(/\r?\n/)[0]).split(" ")[1]);
        if (!(status >= 200 && status < 300)) {
            fail(method + " " + path + " -> HTTP " + (status || "?") + " "
                 + body.substring(0, 400));
        }
        if (!body.replace(/^\s+|\s+$/g, "")) { return {}; }
        return jsonDecode(body, method + " " + path);
    }

    /* Why this job failed, or null if it did not.
     *
     * A run the pipeline itself failed returns rather than raising, so the
     * job's `error` can be empty while its state says FAILED and the reason
     * sits in the report. An adapter reading `error` alone then fell through to
     * "no episodes", which it reported as 16장's 제작 가치 있는 콘텐츠 없음 - a
     * normal ending. That is the one thing a failure must not be mistaken for.
     */
    function failureReason(state) {
        var stated = String((state && state.error) || "");
        var reported;
        if (stated.replace(/^\s+|\s+$/g, "")) { return stated; }
        if (!state || state.state !== FAILED_STATE) { return null; }
        reported = String((state.report && state.report.error) || "");
        return reported.replace(/^\s+|\s+$/g, "") || "the engine did not say why";
    }

    function Engine(options) {
        options = options || {};
        this.host = options.host || DEFAULT_HOST;
        this.port = options.port || DEFAULT_PORT;
        this.apiKey = options.apiKey || "";
        // Set by the .jsx to a Socket-backed function. Without one this object
        // can still build and read messages, which is what the tests use.
        this.transport = options.transport || null;
    }

    Engine.prototype.address = function () {
        return "http://" + this.host + ":" + this.port;
    };

    Engine.prototype.call = function (method, path, body) {
        var request, reply;
        if (!this.transport) {
            fail("this engine has no transport: the editor script must supply one");
        }
        request = buildRequest(method, path, body, this);
        reply = this.transport(request);
        return parseResponse(reply, method, path);
    };

    Engine.prototype.check = function () {
        return this.call("GET", "/api/profiles", null);
    };

    /* Hand the engine the file the editor has open. This is 4장's button: the
     * person pressed it, and from here the engine does 5장's whole list. */
    Engine.prototype.submit = function (sourcePath, options) {
        var body = {source: sourcePath};
        var key;
        if (options) {
            for (key in options) {
                if (options.hasOwnProperty(key)) { body[key] = options[key]; }
            }
        }
        return this.call("POST", "/api/projects", body);
    };

    Engine.prototype.job = function (jobId) {
        return this.call("GET", "/api/jobs/" + String(jobId), null);
    };

    Engine.prototype.episodes = function (projectId) {
        return this.call("GET", "/api/projects/" + String(projectId) + "/episodes", null);
    };

    /* The Common Edit Model for one episode (37장).
     *
     * `mode` is 25장's: new_sequence leaves the operator's own timeline alone,
     * edit_current does not. It is theirs to choose, so it is passed through
     * rather than defaulted silently. */
    Engine.prototype.editModel = function (episodeId, mode) {
        return this.call("POST", "/api/episodes/" + String(episodeId) + "/edit-model",
                         {mode: mode || "new_sequence"});
    };

    return {
        DEFAULT_HOST: DEFAULT_HOST,
        DEFAULT_PORT: DEFAULT_PORT,
        FAILED_STATE: FAILED_STATE,
        EngineError: EngineError,
        Engine: Engine,
        failureReason: failureReason,
        buildRequest: buildRequest,
        parseResponse: parseResponse,
        jsonEncode: jsonEncode,
        byteLength: byteLength
    };
}());

/* ==== aicut_vegas_time.js ==== */
/* The VEGAS Pro half of the arithmetic: frames on the project's own clock.
 *
 *     AI Engine -> Common Edit Model -> VEGAS Adapter -> VEGAS Pro
 *
 * `plugin/common/aicut_model.js` answers what the model means; this file turns
 * that answer into the three numbers a VEGAS event needs, and nothing here
 * touches VEGAS, so it runs under plain node - which is how it is tested on a
 * machine with no VEGAS install on it. `aicut_vegas_body.js` is the part that
 * talks to the application.
 *
 * VEGAS states an event as a start and a length on the timeline, plus the take's
 * offset into the source. There is no end frame at all, so the off-by-one that
 * Resolve and Premiere have to declare does not arise here - a length of 30
 * frames is 30 frames in both directions.
 *
 * ES3 on purpose: VEGAS compiles its .js scripts as JScript.NET, which is not
 * modern JavaScript either.
 */

/*global aicutModel */

var aicutVegasTime = (function (model) {
    "use strict";

    /* Every event to place, in timeline order.
     *
     * Timeline order is the model's, not source order: 2.4 lets a video open on
     * the moment that happened last, and sorting by source would quietly undo
     * the structure the engine chose.
     *
     * Everything is in frames on the project's own clock. VEGAS will happily
     * take seconds and put an event between two frames, and a timeline full of
     * sub-frame offsets is a drift nobody can find by the end of it. */
    function eventList(sequence, fps) {
        var ranges = model.frameRanges(sequence, fps, false);
        var events = [];
        var timeline = 0;
        var i;
        for (i = 0; i < ranges.length; i++) {
            events.push({
                startFrames: timeline,
                lengthFrames: ranges[i].frames,
                offsetFrames: ranges[i].startFrame,
                seconds: ranges[i].frames / fps,
                name: ranges[i].clip.name || "",
                role: ranges[i].clip.role || ""
            });
            timeline += ranges[i].frames;
        }
        return events;
    }

    /* How long the finished timeline is, in frames. */
    function totalFrames(sequence, fps) {
        var events = eventList(sequence, fps);
        var last = events[events.length - 1];
        return last.startFrames + last.lengthFrames;
    }

    function summary(document, sequence, fps) {
        return model.summary(document, sequence, fps, false);
    }

    return {
        eventList: eventList,
        totalFrames: totalFrames,
        summary: summary
    };
}(typeof aicutModel !== "undefined"
    ? aicutModel
    : null));

/* ==== aicut_vegas_body.js ==== */
/* VEGAS Pro Adapter (플러그인 기획안 37장).
 *
 *     AI Engine -> Common Edit Model -> VEGAS Adapter -> VEGAS Pro
 *
 * This file is the last arrow: it reads the Common Edit Model and calls VEGAS,
 * and it decides nothing. Every decision - which spans survive, what order they
 * go in, how seconds become frames - is in `plugin/common/aicut_model.js` and
 * `aicut_vegas_time.js`, which have tests that run without VEGAS.
 *
 * VEGAS compiles one script file at a time: there is no #include and no
 * require. So the file that goes in the Script Menu is BUILT from the shared
 * modules plus this body - `python plugin/vegas/bundle.py` writes it. That is
 * why this file alone is not the installable script: the alternative was a
 * third copy of what the model means, and two copies of that already disagree
 * more often than anyone expects.
 *
 * NOT VERIFIED IN VEGAS. VEGAS Pro is Windows-only and is not present in the
 * environment this was written in, so these API calls have not been executed.
 * They are written against the VEGAS scripting API, whose class names moved
 * from `Sony.Vegas` to `ScriptPortal.Vegas` at version 14 and whose
 * constructors differ between versions - so each one is tried in both shapes
 * rather than assuming this machine's. Treat the first run as the test.
 */


var AICUT_POLL_MS = 3000;

function aicutSay(vegas, message) {
    // VEGAS has no console for a script run from the menu, so the transcript
    // goes to the Script log window, which stays open after the run.
    try {
        vegas.DebugOut(message);
    } catch (e) {
        // Older hosts spell it differently; the dialog at the end still says
        // what happened, so a missing log is not a reason to stop.
    }
}

function aicutReadFile(path) {
    if (!File.Exists(path)) {
        throw new aicutModel.ModelError("no edit model at " + path);
    }
    return File.ReadAllText(path, Encoding.UTF8);
}

function aicutModelFromDialog() {
    var dialog = new OpenFileDialog();
    dialog.Title = "aicut edit model (.json) - cancel to analyse a broadcast";
    dialog.Filter = "aicut edit model (*.json)|*.json";
    if (dialog.ShowDialog() == DialogResult.OK) {
        return dialog.FileName;
    }
    return null;
}

function aicutBroadcastFromDialog() {
    var dialog = new OpenFileDialog();
    dialog.Title = "the broadcast to analyse (4장)";
    dialog.Filter = "video|*.mkv;*.mp4;*.mov;*.ts;*.flv|all files|*.*";
    if (dialog.ShowDialog() == DialogResult.OK) {
        return dialog.FileName;
    }
    return null;
}

/* 36장 9번 AI Engine Connector, over .NET's own HTTP client.
 *
 * The shared connector builds a request and reads a reply; WebClient hands back
 * a body and throws for anything that is not 2xx. So the reply is put back
 * together in the shape the connector parses, which keeps one reader of the
 * engine's answers rather than two. */
function aicutTransport(host, port) {
    return function (request) {
        var split = request.indexOf("\r\n\r\n");
        var head = request.substring(0, split).split("\r\n");
        var body = request.substring(split + 4);
        var line = head[0].split(" ");
        var method = line[0];
        var url = "http://" + host + ":" + port + line[1];
        var client = new WebClient();
        var i, header, colon, answer;

        client.Encoding = Encoding.UTF8;
        for (i = 1; i < head.length; i++) {
            colon = head[i].indexOf(":");
            header = head[i].substring(0, colon);
            if (header == "Host" || header == "Content-Length" || header == "Connection") {
                continue;                     // WebClient sets these itself
            }
            client.Headers.Add(header, head[i].substring(colon + 1).replace(/^\s+/, ""));
        }
        try {
            answer = (method == "GET")
                ? client.DownloadString(url)
                : client.UploadString(url, method, body);
            return "HTTP/1.0 200 OK\r\n\r\n" + answer;
        } catch (exc) {
            var response = exc.Response;
            var status = 0;
            var detail = "";
            if (response != null) {
                status = int(response.StatusCode);
                detail = new StreamReader(response.GetResponseStream(), Encoding.UTF8).ReadToEnd();
                return "HTTP/1.0 " + status + " error\r\n\r\n" + detail;
            }
            // No response at all is the engine not being there, which is the
            // common case by a distance.
            throw new aicutEngine.EngineError(
                "no aicut engine at http://" + host + ":" + port
                    + ". Start it with 'aicut ui'."
            );
        }
    };
}

function aicutEngineFrom(host, port, apiKey) {
    return new aicutEngine.Engine({
        host: host || aicutEngine.DEFAULT_HOST,
        port: port || aicutEngine.DEFAULT_PORT,
        apiKey: apiKey || "",
        transport: aicutTransport(host || aicutEngine.DEFAULT_HOST,
                                 port || aicutEngine.DEFAULT_PORT)
    });
}

/* -- 36장 2~3번 Project Reader / Media Reader --------------------------- */
function aicutProjectFps(project) {
    // The project's own rate, not the model's: a timeline built at another rate
    // slides every cut, and the project the adapter is filling is the one that
    // decides.
    var fps = Number(project.Video.FrameRate);
    if (!(fps > 0)) {
        throw new aicutModel.ModelError(
            "could not read the project's frame rate. Set it in Project "
                + "Properties first."
        );
    }
    return fps;
}

function aicutMedia(vegas, path) {
    if (!File.Exists(path)) {
        throw new aicutModel.ModelError(
            "the model's source is not at " + path + ". Move it back, or re-run "
                + "the analysis against its new location."
        );
    }
    return new Media(path);
}

function aicutNewVideoTrack(project, index, name) {
    // The constructor gained a project argument somewhere between versions.
    try {
        return new VideoTrack(project, index, name);
    } catch (e) {
        return new VideoTrack(index, name);
    }
}

function aicutNewAudioTrack(project, index, name) {
    try {
        return new AudioTrack(project, index, name);
    } catch (e) {
        return new AudioTrack(index, name);
    }
}

function aicutTimecode(frames, fps) {
    try {
        return Timecode.FromFrames(frames);
    } catch (e) {
        // Older hosts count from seconds. frames/fps lands on the grid either
        // way, which is the point of doing the arithmetic in frames first.
        return Timecode.FromSeconds(frames / fps);
    }
}

function aicutNewVideoEvent(project, start, length) {
    try {
        return new VideoEvent(project, start, length);
    } catch (e) {
        return new VideoEvent(start, length);
    }
}

function aicutNewAudioEvent(project, start, length) {
    try {
        return new AudioEvent(project, start, length);
    } catch (e) {
        return new AudioEvent(start, length);
    }
}

/* -- 36장 4~8번 the controllers ----------------------------------------- */
function aicutBuildSequence(vegas, document, sequence, mode) {
    var project = vegas.Project;
    var fps = aicutProjectFps(project);
    var events = aicutVegasTime.eventList(sequence, fps);
    var media = aicutMedia(vegas, aicutModel.mediaPath(document, "source"));
    var name = aicutModel.timelineName(document, sequence);
    var videoTrack, audioTrack, videoStream, audioStream;
    var i, entry, videoEvent, audioEvent, take;

    if (mode != "edit_current" && project.Tracks.Count > 0) {
        // 25장 mode A leaves the operator's own edit alone: new tracks beside
        // it, never events dropped into theirs. Appending into an edit somebody
        // is working on is only ever done because they asked for it by name.
        aicutSay(vegas, "this project already has tracks; adding new ones for " + name);
    }

    videoStream = media.GetVideoStreamByIndex(0);
    if (videoStream == null) {
        throw new aicutModel.ModelError(
            "VEGAS sees no video stream in " + aicutModel.baseName(media.FilePath)
        );
    }
    try {
        audioStream = media.GetAudioStreamByIndex(0);
    } catch (e) {
        audioStream = null;
    }

    videoTrack = aicutNewVideoTrack(project, project.Tracks.Count, name);
    project.Tracks.Add(videoTrack);
    if (audioStream != null) {
        // 24장 gives 원본 음성 its own track. VEGAS does not link A and V the
        // way the other two editors do, so the source audio is laid down
        // alongside rather than assumed to come with the picture.
        audioTrack = aicutNewAudioTrack(project, project.Tracks.Count, name + " 원본 음성");
        project.Tracks.Add(audioTrack);
    }

    for (i = 0; i < events.length; i++) {
        entry = events[i];
        videoEvent = aicutNewVideoEvent(
            project,
            aicutTimecode(entry.startFrames, fps),
            aicutTimecode(entry.lengthFrames, fps)
        );
        videoTrack.Events.Add(videoEvent);
        take = videoEvent.AddTake(videoStream);
        take.Offset = aicutTimecode(entry.offsetFrames, fps);

        if (audioStream != null) {
            audioEvent = aicutNewAudioEvent(
                project,
                aicutTimecode(entry.startFrames, fps),
                aicutTimecode(entry.lengthFrames, fps)
            );
            audioTrack.Events.Add(audioEvent);
            take = audioEvent.AddTake(audioStream);
            take.Offset = aicutTimecode(entry.offsetFrames, fps);
        }
    }

    aicutSay(vegas, aicutVegasTime.summary(document, sequence, fps));
    var dropped = aicutModel.droppedSpans(sequence, fps);
    for (i = 0; i < dropped.length; i++) {
        aicutSay(vegas, "  skipped " + dropped[i][0].toFixed(3) + "-"
                 + dropped[i][1].toFixed(3) + "s: shorter than one frame at " + fps + " fps");
    }
    var placed = aicutModel.audioClips(sequence);
    if (placed.length) {
        // 24장 puts BGM and 효과음 on their own tracks. The model states a path
        // and a time; laying them down would mean deciding their level and
        // length here, which is 8.2's to state and not the adapter's to invent.
        aicutSay(vegas, "  " + placed.length + " audio placement(s) the model asks for are not applied:");
        for (i = 0; i < placed.length; i++) {
            aicutSay(vegas, "    " + placed[i].track + " " + (placed[i].clip.path || "")
                     + " at " + Number(placed[i].clip.timeline_position_sec || 0).toFixed(2) + "s");
        }
    }
    var lines = aicutModel.subtitles(sequence);
    if (lines.length) {
        aicutSay(vegas, "  " + lines.length + " caption(s) in the model; import an .srt "
                 + "for them (`aicut export <plan> --format srt`)");
    }
    return videoTrack;
}

function aicutBuildFromFile(vegas, path, mode) {
    var document = aicutModel.parse(aicutReadFile(path), path);
    var list = aicutModel.sequences(document);
    var built = [];
    var i;
    for (i = 0; i < list.length; i++) {
        built.push(aicutBuildSequence(vegas, document, list[i], document.mode || mode));
    }
    return built;
}

/* 4장's button: hand the engine the broadcast, wait, build what comes back.
 *
 * The plugin analyses nothing (35장). VEGAS can say what media is in the
 * project, but the person may have several things open, so the broadcast is
 * picked in a dialog rather than guessed at. */
function aicutBuildFromEngine(vegas, sourcePath, mode, engine) {
    var built = [];
    var state, line, last = "", failed, episodes, document, list, i, j;
    var job, jobId, projectId;

    engine = engine || aicutEngineFrom(null, null, null);
    aicutSay(vegas, "analysing " + aicutModel.baseName(sourcePath));
    job = engine.submit(sourcePath);
    jobId = job.job_id || job.id;
    projectId = job.project_id || "";
    if (!jobId) {
        throw new aicutEngine.EngineError("the engine did not return a job id");
    }

    // 26장's progress panel is this loop's output. The engine names its own
    // stages; repeating them is the panel, and inventing stage names here would
    // describe a pipeline that is not the one running.
    while (true) {
        state = engine.job(jobId);
        line = state.state || state.status || "";
        if (line && line != last) {
            aicutSay(vegas, "  " + line);
            last = line;
        }
        if (!state.running) { break; }
        System.Threading.Thread.Sleep(AICUT_POLL_MS);
    }
    failed = aicutEngine.failureReason(state);
    if (failed) {
        throw new aicutEngine.EngineError("the analysis failed: " + failed);
    }
    projectId = state.project_id || projectId;
    if (!projectId) {
        throw new aicutEngine.EngineError("the engine did not say which project it made");
    }

    episodes = engine.episodes(projectId);
    if (!episodes || !episodes.length) {
        // 16장: 제작 가치 있는 콘텐츠 없음 is a normal ending, not a failure.
        aicutSay(vegas, "the engine found nothing worth producing in this broadcast (16장)");
        return built;
    }
    for (i = 0; i < episodes.length; i++) {
        document = aicutModel.validated(engine.editModel(episodes[i].episode_id, mode));
        list = aicutModel.sequences(document);
        for (j = 0; j < list.length; j++) {
            built.push(aicutBuildSequence(vegas, document, list[j], mode));
        }
    }
    return built;
}

class EntryPoint {
    function FromVegas(vegas : Vegas) {
        var mode = Environment.GetEnvironmentVariable("AICUT_TIMELINE_MODE");
        var modelPath = Environment.GetEnvironmentVariable("AICUT_MODEL");
        var host = Environment.GetEnvironmentVariable("AICUT_ENGINE_HOST");
        var portText = Environment.GetEnvironmentVariable("AICUT_ENGINE_PORT");
        var apiKey = Environment.GetEnvironmentVariable("AICUT_API_KEY");
        var broadcast;
        if (!mode) { mode = "new_sequence"; }
        try {
            if (!modelPath) { modelPath = aicutModelFromDialog(); }
            if (modelPath) {
                aicutBuildFromFile(vegas, modelPath, mode);
            } else {
                // Cancelling the model dialog is how the operator says "just do
                // it" - the button of 4장 - so it asks which broadcast instead
                // of stopping.
                broadcast = aicutBroadcastFromDialog();
                if (broadcast) {
                    aicutBuildFromEngine(
                        vegas, broadcast, mode,
                        aicutEngineFrom(host, portText ? Number(portText) : 0, apiKey)
                    );
                }
            }
        } catch (e) {
            // A dialog, because a script run from the menu has no console open
            // and a silent failure looks like the plugin did nothing.
            MessageBox.Show("aicut: " + (e.message || e), "aicut");
            aicutSay(vegas, "aicut: " + (e.message || e));
        }
    }
}

