"""Build the single script file VEGAS Pro's Script Menu wants.

VEGAS compiles one file at a time. There is no `#include` (Premiere's way) and
no `sys.path` (Resolve's way), so the shared modules cannot be imported from
beside the script - they have to be in it.

The alternative was a third copy of what the Common Edit Model means, written
in JScript for this one editor. Two copies of that already disagree more often
than anyone expects, and 37장 put the layer there precisely so they would not.
So the shared modules are concatenated with the VEGAS body, in order, and the
result is what gets installed:

    python plugin/vegas/bundle.py                 -> plugin/vegas/aicut_vegas.js
    python plugin/vegas/bundle.py --out <path>    -> anywhere else

Standard library only, and it never imports aicut: a person who copied `plugin/`
onto a Windows box can build the script with the Python that is already there.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMMON = os.path.join(os.path.dirname(HERE), "common")

#: In dependency order: the model reader, the engine connector, this editor's
#: own arithmetic, then the body that calls VEGAS. The body is last because it
#: is the only part that names VEGAS types.
PARTS = (
    os.path.join(COMMON, "aicut_model.js"),
    os.path.join(COMMON, "aicut_engine.js"),
    os.path.join(HERE, "aicut_vegas_time.js"),
    os.path.join(HERE, "aicut_vegas_body.js"),
)

HEADER = """\
/* GENERATED - do not edit this file.
 *
 * Built by `python plugin/vegas/bundle.py` from, in order:
{listing}
 *
 * Edit those and build again. VEGAS compiles one script file at a time, which
 * is the only reason this file exists; the parts above are what the tests run.
 */

"""

#: node's module tail, which JScript.NET has no idea about. It is what lets the
#: same modules be tested under node, and it must not reach the bundle - VEGAS
#: would stop at `module` being undefined before a line of the script ran.
NODE_TAIL = "if (typeof module !== \"undefined\" && module.exports)"

#: node's fallback import in the editor-specific modules, for the same reason.
NODE_REQUIRE = "require("


def strip_node(source: str, path: str) -> str:
    """Remove the lines that only exist so node can load the module."""
    kept = []
    for line in source.splitlines():
        if line.startswith(NODE_TAIL):
            continue
        if NODE_REQUIRE in line and "typeof" not in line:
            # `}(typeof aicutModel !== "undefined" ? aicutModel : require(...))`
            # spans two lines; the require half is the one that must go, and the
            # conditional half stays because the bundle really does define it.
            line = line.replace(
                ": require(\"../common/aicut_model.js\")", ": null"
            )
        kept.append(line)
    return "\n".join(kept).rstrip() + "\n"


def split_imports(source: str):
    """Lift `import ScriptPortal.Vegas;` and its neighbours out of the body.

    JScript.NET wants its imports before anything else in the file, and the body
    they belong to is concatenated last. Left where they are, the script does
    not compile - and a script that does not compile says so in a dialog with a
    line number that means nothing to the person reading it.
    """
    imports = []
    body = []
    for line in source.splitlines():
        if line.startswith("import ") and line.rstrip().endswith(";"):
            imports.append(line)
        else:
            body.append(line)
    return imports, "\n".join(body).rstrip() + "\n"


def build() -> str:
    # Forward slashes and nothing else: the file this builds is committed, and a
    # build on Windows wrote `plugin\common\aicut_model.js` into the header -
    # a file that differed from the one in the repository by the separator of
    # whoever ran it last.
    listing = "\n".join(
        " *   {}".format(
            os.path.relpath(part, os.path.dirname(os.path.dirname(HERE)))
            .replace(os.sep, "/")
        )
        for part in PARTS
    )
    imports = []
    pieces = []
    for part in PARTS:
        with open(part, "r", encoding="utf-8") as handle:
            found, body = split_imports(strip_node(handle.read(), part))
            for line in found:
                if line not in imports:
                    imports.append(line)
            pieces.append("/* ==== {} ==== */\n".format(os.path.basename(part)))
            pieces.append(body)
            pieces.append("\n")

    out = [HEADER.format(listing=listing)]
    if imports:
        out.append("\n".join(imports) + "\n\n")
    out.extend(pieces)
    return "".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="bundle.py",
        description="Build the VEGAS Pro script from the shared modules",
    )
    parser.add_argument("--out", default=os.path.join(HERE, "aicut_vegas.js"),
                        help="where to write it (default: beside this script)")
    args = parser.parse_args(argv)

    text = build()
    # newline="" so Python does not translate the line endings: on Windows it
    # would write CRLF, and the same reason applies - one generated file, the
    # same bytes wherever it was built.
    with open(args.out, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    print("{} lines -> {}".format(len(text.splitlines()), args.out))
    print("copy it into VEGAS's Script Menu folder:")
    print(r"  C:\Program Files\VEGAS\VEGAS Pro <version>\Script Menu")
    return 0


if __name__ == "__main__":
    sys.exit(main())
